### ISSUE TITLE
django.contrib.admin urls don't work on Django 1.10

### ISSUE THREAD

**Issue by mikebryant** [mikebryant/django-autoconfig#37]
```
Traceback (most recent call last):
  File "/home/m/git/python-blueprints/lists/tests.py", line 11, in test_home_page_returns_correct_html
    response = self.client.get(reverse('lists/home'))
  File "/export/home/m/virtualenvs/python-blueprints/local/lib/python2.7/site-packages/django/urls/base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/export/home/m/virtualenvs/python-blueprints/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 344, in _reverse_with_prefix
    self._populate()
  File "/export/home/m/virtualenvs/python-blueprints/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 209, in _populate
    for name in pattern.reverse_dict:
  File "/export/home/m/virtualenvs/python-blueprints/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 242, in reverse_dict
    self._populate()
  File "/export/home/m/virtualenvs/python-blueprints/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 199, in _populate
    p_pattern = pattern.regex.pattern
AttributeError: 'tuple' object has no attribute 'regex'
```
